db:
  image: postgres:9.4
  env_file:
    - ./examples/docker/postgres.env
elastic:
  image: elasticsearch:2
redis:
  image: redis
prompg:
  image: prom/pushgateway
promsrv:
  build: ./examples/docker/prometheus/
  links:
    - prompg
    - inventory_worker
    - store_worker
    - processor_worker
nginx:
  image: nginx
  ports:
    - "443:443"
  links:
    - web
    - promsrv
  volumes:
    - ./examples/docker/nginx/conf.d/:/etc/nginx/conf.d/
    - ./examples/docker/tls:/etc/nginx/tls
app:
  build: .
  entrypoint: /zentral/docker-entrypoint.py
  environment:
    ZENTRAL_CONF_DIR: /zentral/examples/conf/
    POSTGRES_HOST: db
  env_file:
    - ./examples/docker/postgres.env
  volumes:
    - .:/zentral
  restart: onfailure:10
web:
  extends: app
  command: runserver
  links:
  - db
  - elastic
  - redis
inventory_worker:
  extends: app
  command: inventory_worker
  links:
  - db
  - prompg
  - redis
store_worker:
  extends: app
  command: store_worker
  links:
  - db
  - elastic
  - prompg
  - redis
processor_worker:
  extends: app
  command: processor_worker
  links:
  - db
  - prompg
  - redis
