db:
  image: postgres:9.4
  env_file:
    - ./conf/start/docker/postgres.env
elastic:
  image: elasticsearch:2
rabbitmq:
  image: rabbitmq:3
prompg:
  image: prom/pushgateway
promsrv:
  build: ./conf/start/docker/prometheus/
  links:
    - prompg
    - inventory_worker
    - store_worker
    - processor_worker
nginx:
  image: nginx
  ports:
    - "443:443"
  links:
    - web
    - promsrv
  volumes:
    - ./conf/start/docker/nginx/conf.d/:/etc/nginx/conf.d/
    - ./conf/start/docker/tls:/etc/nginx/tls
app:
  build: .
  entrypoint: /zentral/docker-entrypoint.py
  environment:
    ZENTRAL_CONF_DIR: /zentral/conf/start/zentral/
    POSTGRES_HOST: db
  env_file:
    - ./conf/start/docker/postgres.env
  volumes:
    - .:/zentral
  restart: onfailure:10
web:
  extends: app
  command: runserver
  links:
    - db
    - elastic
    - rabbitmq
inventory_worker:
  extends: app
  command: inventory_worker
  links:
    - db
    - prompg
    - rabbitmq
store_worker:
  extends: app
  command: store_worker
  links:
    - db
    - elastic
    - prompg
    - rabbitmq
processor_worker:
  extends: app
  command: processor_worker
  links:
    - db
    - prompg
    - rabbitmq
