version: '2'

services:
  db:
    image: postgres:9.6
    env_file:
      - ./conf/start/docker/postgres.env
    networks:
      default:
        aliases:
          - postgres
  rabbitmq:
  elastic:
    image: elasticsearch:5
    networks:
      default:
        aliases:
          - elasticsearch
  rabbitmq:
    image: rabbitmq:3
  promsrv:
    build: ./conf/start/docker/prometheus/
  nginx:
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - promsrv
      - web
    volumes:
      - ./conf/start/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/start/docker/tls:/etc/nginx/tls
  inventory_worker:
    extends:
      file: docker-compose.common.yml
      service: app
    command: inventory_worker
    depends_on:
      - db
      - rabbitmq
  processor_worker:
    extends:
      file: docker-compose.common.yml
      service: app
    command: processor_worker
    depends_on:
      - db
      - rabbitmq
  store_worker:
    extends:
      file: docker-compose.common.yml
      service: app
    command: store_worker
    depends_on:
      - db
      - elastic
      - rabbitmq
  web:
    extends:
      file: docker-compose.common.yml
      service: app
    command: runserver
    depends_on:
      - db
      - elastic
      - rabbitmq

networks:
  default:
