version: '2'

services:
  simplesamlphp:
    build: ./conf/saml2/docker/simplesamlphp/
    ports:
      - "80:80"
  web:
    environment:
      ZENTRAL_SAML2_IDP_NAME: Simple SAML PHP
      ZENTRAL_SAML2_IDP_METADATA_FILE: /zentral/conf/saml2/zentral/saml2_idp_metadata.xml
