global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'zentral_pushgateway'
    target_groups:
      - targets: ['prompg:9091']

  - job_name: 'zentral_processors'
    target_groups:
      - targets: ['processor_worker:8100']
