global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zentral_inventory'
    metrics_path: '/inventory/prometheus_metrics/'
    bearer_token: 'CHANGE ME!!!'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'zentral_inventory_worker_dummy'
    static_configs:
      - targets: ['workers:9900']

  - job_name: 'zentral_jamf_events_preprocessor'
    static_configs:
      - targets: ['workers:9901']

  - job_name: 'zentral_processor_worker'
    static_configs:
      - targets: ['workers:9902']

  - job_name: 'zentral_store_worker_elasticsearch'
    static_configs:
      - targets: ['workers:9903']
