global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zentral_inventory'
    metrics_path: '/inventory/prometheus_metrics/'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'zentral_processors'
    static_configs:
      - targets: ['processor_worker:8100']
