filebeat:
  registry_file: /tmp/filebeat/registry
  prospectors:
    - paths:
        - /usr/local/jss/logs/JAMFChangeManagement.log
      input_type: log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      fields:
        jamf_instance:
          host: jss.apfelwerk.de

output:
  logstash:
    hosts:
      - "zentral:5044"
    ssl:
      certificate_authorities: 
        - "/Users/flaco/dev/zentral/conf/start/docker/tls/zentral_fullchain.crt"

logging:
  level: info
  to_files: true
  to_syslog: false
  files:
    path: /tmp/filebeat
    name: jamf_logs
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 7
